version: 2.1
executors:
  ubuntu:
    docker:
      - image: circleci/node:11.8.0
aliases:
  - &attach_workspace
    attach_workspace:
      at: ~/installer
  - &restore_cache
    keys:
      - cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
  - &install_node_dependencies
    name: Install node dependencies
    command: npm install
  - &download_assets
    name: Download assets
    command: npm run download-assets
  - &build
    name: Build binaries
    command: npm run build
  - &save_cache
    key: cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
    paths:
      - ~/.npm
      - ~/.cache
  - &store_artifacts
    path: ~/installer/build
  # - &test_all
  #   name: Run all tests
  #   command: 'npm test'
  # - &test_smoke
  #   name: Run smoke tests
  #   command: 'npm run smoke-test'
executors:
  cypress:
    working_directory: ~/installer
    docker:
      - image: cypress/base:10
        environment:
          term: xterm
workflows:
  version: 2
  smoke-test:
    jobs:
      - smoke-test
    triggers:
      - schedule:
          cron: "40 * * * *"
          filters:
            branches:
              only:
                - master
  all:
    jobs:
      - test
jobs:
  test:
    executor: ubuntu
    steps:
      - checkout
      - *attach_workspace
      - restore_cache: *restore_cache
      - run: *install_node_dependencies
      - run: *download_assets
      - save_cache: *save_cache
      - run: *build
      - store_artifacts: *store_artifacts

      # - run: *test_all
  # smoke-test:
  #   executor: cypress
  #   steps:
  #     - checkout
  #     - *attach_workspace
  #     - restore_cache: *restore_cache
  #     - run: *install_web
  #     - run: *verify_cypress
  #     - save_cache: *save_cache
  #     - run: *build_web
  #     - run: *install_server
  #     - run: *test_smoke
